### PR TITLE
Fixed build for modern macOS and GCC

### PR DESCRIPTION
**Pull request by christoff-buerger**
Fixed build bug for macOS (version 10.13.6, macOS High Sierra). Ypsilon can now be build with GCC 9.2.0 or Apple LLVM version 10.0.0 (clang 1000.10.44.4).

Also added a `.gitignore` file to avoid commits of generated artefacts.

### CODE REVIEW

**Comment by imrehg** [comment]
Thanks for the fixup, will be checking out! Sorry for the delay, I didn't quite get the notification for it.
I forked this from Google Code to preserve, have to check whether this is a good place to maintain this code.

**Comment by imrehg** [comment]
This doesn't seem to work on latest macOS (12.3.1, Monterey), as 32bit support is no longer (fully) there.

```shell
ld: symbol(s) not found for architecture i386
```

**Comment by christoff-buerger** [comment]
@imrehg: Unfortunately I only have access to macOS 10.13.6, on my good old macbook air from 2011. Hence, I can not test nor fix any issues on a newer macOS (because I can not upgrade macOS anymore -- the macbook air 2011 is stuck on metal for graphics and Apple does not support it anymore in newer macOS).

But I am sure there are **new** build issues. Emphasis on **new**.
I assume, that this pull request's fixes are anyway required.

I can't say what is best for you to progress: accept the pull request or not. My feeling is, to accept it and then look forward to fix the new issues. A lot of time passed since I made the request.

Btw, just a side note: I am regularly checking Ypsilon in my RACR library builds. It passes fine (on the old macbook air 2011).

**Comment by christoff-buerger** [comment]
I just build on my old macbook air 2011 with macOS 10.13.6 anew with gcc 11.2.0.
It works fine.
